### ISSUE TITLE
Not able to install as extension in chrome

### ISSUE THREAD

**Issue by rakitanc** [WonSign/sorvyt#1]
Please guide it

chrome version 103.0.5060.114 (Official Build) (64-bit)

**Comment by WonSign** [comment]
Sorry, I haven't written it on Readme yet.
This application is currently under development.
We will be deploying Chrome Extension in future updates.

**Comment by rakitanc** [comment]
> Sorry, I haven't written it on Readme yet. This application is currently under development. We will be deploying Chrome Extension in future updates.

Please make it quickly brother. We are waiting

**Comment by WonSign** [comment]
I opened a website. Please use the website until the Chrome Extension is developed.

**Comment by rakitanc** [comment]
> I opened a website. Please use the website until the Chrome Extension is developed.

Wow man that's cool. I just tried it but it's not loading the full videos only limited number. can you please see that

https://www.sorvyt.com/result?channelId=UCZsJ1_bm-aCd6l4BJHsIx5Q&order=date

**Comment by WonSign** [comment]
It is designed to load only 50 videos.
Because I thought 50 videos arranged on a different basis from YouTube should be enough.

**Comment by rakitanc** [comment]
Can you please make them to load all as it's easier to find the exact videos i am looking for. That was the main purpose actually

**Comment by WonSign** [comment]
It will be updated soon.

**Comment by rakitanc** [comment]
> It will be updated soon.

You are awesome mate. One feature i can suggest you to add is where one can find videos on a  channel by year. It would be really cool if that's possible

**Comment by rakitanc** [comment]
> It will be updated soon.

And one bug i noticed that in all the filters you can't sort by high or low. So please fix that
